import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium, webkit } from 'playwright';
import { sampleResult } from './rank-fixture.mjs';

const baseURL = process.env.APP_URL || 'http://127.0.0.1:4274';
const samplePath = process.argv[2];
const purrloin = process.argv[3] === 'purrloin';
const imageName = purrloin ? 'チョロネコ' : 'デルビル';
const imageIVs = purrloin ? ['1', '4', '15'] : ['8', '3', '11'];
if (!samplePath) throw new Error('Pass the Houndour appraisal screenshot path as the first argument.');
await mkdir('artifacts', { recursive: true });

for (const browserType of [chromium, webkit]) {
    const browser = await browserType.launch();
    try {
        const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
        const page = await context.newPage();
        let apiRequests = 0;
        await context.route('**/api/rank', async route => {
            apiRequests++;
            const request = route.request();
            assert.deepEqual(request.postDataJSON(), { pokemonId: 'houndour', ivs: [8, 3, 11] });
            assert.equal(request.headers().authorization, 'Bearer test-only-access-code');
            await route.fulfill({ json: sampleResult() });
        });
        const errors = [];
        const externalRequests = [];
        page.on('pageerror', error => errors.push(error.message));
        page.on('request', request => {
            if (request.url().startsWith('http') && new URL(request.url()).origin !== new URL(baseURL).origin) externalRequests.push(request.url());
        });
        await page.goto(baseURL);
        await page.locator('#access-code').fill('test-only-access-code');
        await page.locator('#image-file').setInputFiles(samplePath);
        await page.waitForFunction(() => !document.querySelector('#image-file').disabled, undefined, { timeout: 60000 });
        assert.equal(await page.locator('#pokemon').inputValue(), imageName);
        assert.deepEqual(await Promise.all([0, 1, 2].map(index => page.locator(`#iv-${index}`).inputValue())), imageIVs);
        if (purrloin) await page.locator('#sample-button').click();
        await page.locator('button[type=submit]').click();
        await page.waitForSelector('.result-card');
        assert.equal(await page.locator('.result-card').count(), 2);
        assert.match(await page.locator('.result-card').nth(1).innerText(), /1,654/);
        assert.match(await page.locator('.result-card').nth(1).innerText(), /1,495/);
        assert.deepEqual(externalRequests, []);
        assert.deepEqual(errors, []);
        await page.screenshot({ path: `artifacts/${browserType.name()}-mobile.png`, fullPage: true });
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
        await page.locator('[data-cap="2500"]').click();
        assert.match(await page.locator('.result-card').nth(1).innerText(), /2,338/);
        await page.locator('#max-level').selectOption('40');
        assert.doesNotMatch(await page.locator('.result-card').nth(1).innerText(), /2,338/);
        assert.equal(apiRequests, 1);
        await page.locator('#max-level').selectOption('51');
        assert.match(await page.locator('.result-card').nth(1).innerText(), /2,496/);
        assert.doesNotMatch(await page.locator('.result-card').nth(1).innerText(), /SCP|未取得/);
        await page.locator('#iv-0').fill('16');
        assert.equal(await page.locator('.result-card').count(), 0);
        await page.locator('button[type=submit]').click();
        assert.match(await page.locator('#form-error').innerText(), /0〜15/);
        await page.locator('#pokemon').fill('存在しない名前');
        await page.locator('button[type=submit]').click();
        assert.match(await page.locator('#form-error').innerText(), /候補/);
        await page.locator('#image-file').setInputFiles({ name: 'invalid.txt', mimeType: 'text/plain', buffer: Buffer.from('invalid') });
        await page.waitForFunction(() => !document.querySelector('#image-file').disabled);
        assert.match(await page.locator('#scan-status').innerText(), /PNG/);
        await page.locator('#image-file').setInputFiles({ name: 'broken.png', mimeType: 'image/png', buffer: Buffer.from('invalid') });
        await page.waitForFunction(() => !document.querySelector('#image-file').disabled);
        assert.ok(await page.locator('#scan-status.error').count());
        await page.locator('#image-file').setInputFiles(samplePath);
        await page.locator('#cancel-scan').click();
        await page.waitForFunction(() => !document.querySelector('#image-file').disabled);
        assert.equal(await page.locator('#pokemon').inputValue(), '');
        await page.locator('#image-file').setInputFiles(samplePath);
        await page.waitForFunction(() => !document.querySelector('#image-file').disabled, undefined, { timeout: 60000 });
        assert.equal(await page.locator('#pokemon').inputValue(), imageName);
        if (purrloin) await page.locator('#sample-button').click();
        await page.locator('button[type=submit]').click();
        await page.setViewportSize({ width: 320, height: 740 });
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
        await page.setViewportSize({ width: 1280, height: 1000 });
        await page.evaluate(() => scrollTo(0, 0));
        await page.screenshot({ path: `artifacts/${browserType.name()}-desktop.png`, fullPage: true });
        console.log(`${browserType.name()}: browser checks passed.`);
        const recoveryPage = await context.newPage();
        let attempt = 0;
        let releaseRank;
        const rankGate = new Promise(resolve => { releaseRank = resolve; });
        await recoveryPage.route('**/api/rank', async route => {
            attempt++;
            if (attempt === 1) return route.fulfill({ status: 503, json: { error: '順位を取得できませんでした。' } });
            if (attempt === 2) await rankGate;
            await route.fulfill({ json: sampleResult() }).catch(() => {});
        });
        await recoveryPage.goto(baseURL);
        await recoveryPage.locator('#sample-button').click();
        await recoveryPage.locator('#access-code').fill('test-only-access-code');
        await recoveryPage.locator('button[type=submit]').click();
        await recoveryPage.locator('#results').getByText('計算に使うデータ ↗', { exact: true }).waitFor();
        assert.equal(await recoveryPage.locator('button[type=submit]').isEnabled(), true);
        const pendingRank = recoveryPage.waitForRequest('**/api/rank');
        await recoveryPage.locator('button[type=submit]').click();
        await pendingRank;
        assert.equal(await recoveryPage.locator('button[type=submit]').isDisabled(), true);
        const cancelledRank = recoveryPage.waitForEvent('requestfailed', request => request.url().endsWith('/api/rank'));
        await recoveryPage.locator('#iv-0').fill('9');
        await cancelledRank;
        releaseRank();
        assert.equal(await recoveryPage.locator('.result-card').count(), 0);
        await recoveryPage.locator('#iv-0').fill('8');
        await recoveryPage.locator('button[type=submit]').click();
        await recoveryPage.waitForSelector('.result-card');
        assert.match(await recoveryPage.locator('.result-summary').innerText(), /8 \/ 3 \/ 11/);
        console.log(`${browserType.name()}: API failure, retry and stale-result cancellation passed.`);
        await context.close();
        const blockedContext = await browser.newContext();
        const blockedPage = await blockedContext.newPage();
        let release;
        const gate = new Promise(resolve => { release = resolve; });
        await blockedPage.route('**/ocr/core/**', async route => { await gate; await route.abort().catch(() => {}); });
        await blockedPage.goto(baseURL);
        for (let attempt = 0; attempt < 2; attempt++) {
            const created = blockedPage.waitForEvent('worker');
            const requested = blockedPage.waitForRequest('**/ocr/core/**');
            await blockedPage.locator('#image-file').setInputFiles(samplePath);
            const worker = await created;
            await requested;
            assert.equal(await blockedPage.locator('#pokemon').isDisabled(), true);
            assert.equal(await blockedPage.locator('#iv-0').isDisabled(), true);
            assert.equal(await blockedPage.locator('button[type=submit]').isDisabled(), true);
            const closed = worker.waitForEvent('close');
            await blockedPage.locator('#cancel-scan').click();
            await closed;
            await blockedPage.waitForFunction(() => !document.querySelector('#image-file').disabled);
            assert.equal(blockedPage.workers().length, 0);
            assert.equal(await blockedPage.locator('#pokemon').isDisabled(), false);
        }
        release();
        await blockedContext.close();
        console.log(`${browserType.name()}: initialization cancellation passed.`);
        if (browserType === chromium) {
            const failureContext = await browser.newContext();
            const failurePage = await failureContext.newPage();
            await failureContext.route('**/api/rank', route => route.fulfill({ json: sampleResult() }));
            await failurePage.route('**/ocr/worker.min.js', route => route.abort());
            await failurePage.goto(baseURL);
            await failurePage.locator('#image-file').setInputFiles(samplePath);
            await failurePage.waitForFunction(() => !document.querySelector('#image-file').disabled, undefined, { timeout: 60000 });
            assert.match(await failurePage.locator('#scan-status').innerText(), /名前/);
            assert.deepEqual(await Promise.all([0, 1, 2].map(index => failurePage.locator(`#iv-${index}`).inputValue())), imageIVs);
            if (purrloin) await failurePage.locator('#sample-button').click();
            await failurePage.locator('#pokemon').fill('デルビル');
            await failurePage.locator('#access-code').fill('test-only-access-code');
            await failurePage.locator('button[type=submit]').click();
            await failurePage.waitForSelector('.result-card');
            assert.equal(await failurePage.locator('.result-card').count(), 2);
            await failureContext.close();
            console.log('OCR asset failure: manual recovery passed.');
        }
    } finally { await browser.close(); }
}
